baseURL = "https://emu.team/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Emu Exploit"
theme = "gokarna"
publishDir = "docs"
enableRobotsTXT = true

[params]
  avatarURL = "/images/avatar.png"
  avatarSize = "size-l"
  description = "Aussie CTF Team"
  accentColor = "##f9b54c"
  metaKeywords = ["ctf", "australia", "cool"]
  footer = "Emu Exploit"

  socialIcons = [
      {name = "twitter", url = "https://twitter.com/EmuExploit"},
      {name = "ctftime", url = "https://ctftime.org/team/160273"},
    ]

[permalinks]
  posts = "/:title"

[menu]
#  [[menu.main]]
#    identifier = "posts"
#    url = "/posts/"
#    pre = ""
#    post = ""
#    name = "Posts"
#    weight = 1
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "members"
    name = "Members"
    url = "/members"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

  [[menu.main]]
    identifier = "perth-socialware"
    name = "Perth Socialware"
    url = "/perth-socialware"
    weight = 5
